local SCRIPT_TITLE = 'Transpose notes'

--[[

lua file name: TransposeNotesPanel.lua

Transpose notes panel to shift pitch notes from semitones
in selected groups or all groups in all tracks in the project.

Notice: Works only with script panel 
		introduced with Synthesizer V version >= 2.1.2

Update: Creation
		Add a TextArea note information with check box
		Add a check box to play selected notes
		Update note display with position A=>A4

2025 - JF AVILES
--]]

function getClientInfo()
	return {
		name = SV:T(SCRIPT_TITLE),
		-- category = "_JFA_Panels",
		author = "JFAVILES",
		versionNumber = 4,
		minEditorVersion = 131329,
		type = "SidePanelSection"
	}
end

-- Generated by JFA TranslateScripts.lua
function getTranslations(langCode)
	return getArrayLanguageStrings()[langCode]
end

-- Generated by JFA TranslateScripts.lua
function getArrayLanguageStrings()
	return {
		["en-us"] = {
			{"Version", "Version"},
			{"author", "author"},
			{"minEditorVersion", "minEditorVersion"},
			{"Transpose notes", "Transpose notes"},
			{"Infos on selected notes", "Infos on selected notes"},
			{"Note: ", "Note: "},
			{"Lyrics: ", "Lyrics: "},
			{"Time: ", "Time: "},
			{"Track time: ", "Track time: "},
			{"Blicks: ", "Blicks: "},
			{"Selected notes: ", "Selected notes: "},
			{"...", "..."},
			{"Notes: ", "Notes: "},
			{"Select at least one group!", "Select at least one group!"},
			{"Transpose", "Transpose"},
			{"Select a value", "Select a value"},
			{"+", "+"},
			{"to", "to"},
			{"in all tracks", "in all tracks"},
			{"Limited to selected groups", "Limited to selected groups"},
			{"Display note infos", "Display note infos"},
			{"Play notes", "Play notes"},
			{"Transpose notes (semitones)", "Transpose notes (semitones)"},
		},
	}
end

-- Define a class "NotesObject"
NotesObject = {
	displayVersion = true,	-- display version
	displayAuthor = false,	-- display author
	errorMessages = {},
	hostinfo = nil,
	osType = "",
	osName = "",
	hostName = "",
	languageCode = "", 
	hostVersion = "",
	hostVersionNumber = 0,
	controls = {},				-- controls panel
	statusTextValue = nil,   	-- text panel
	statusNoteValue = nil,   	-- text panel
	infosToDisplay = "",
	displayBlicks = false,
	displayBlicksSize = 80,
	isLimitedToSelectedGroups = true,
	isDisplayNoteInfos = false, -- Display note information (check box)
	isPlayNoteActive = false,
	transposeSemitone = 0,
	transposeMinValue = -12,
	transposeMaxValue = 12,
	transposeInterval = 1,
	updatedGroupChar = "*",
	keyNames = {},
	currentPlayheadPos = 0,
	debug = false,
	logs = {}
}


-- Constructor method for the NotesObject class
function NotesObject:new()
    local notesObject = {}
    setmetatable(notesObject, self)
    self.__index = self
	
	self:getHostInformations()
	
	self.controls = self:getControls()
	
	self:initializeControlsValues()
	self:setControlsCallback()
	
	self.transposeNotesValue = SV:create("WidgetValue")
	
	self.statusTextValue = SV:create("WidgetValue")
	self.statusTextValue:setValue("")
	self.statusTextValue:setEnabled(false)
	
	self.statusNoteValue = SV:create("WidgetValue")
	self.statusNoteValue:setValue("")
	self.statusNoteValue:setEnabled(false)
	
	self:setButtonTransposeNotesControlCallback()

	local infos = getClientInfo()
	
	self.keyNames = {"C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B"}
	
	if self.displayBlicks then
		self.displayBlicksSize = 100
	end
	self.infosToDisplay = ""
	if self.displayVersion then
		self.infosToDisplay = self.infosToDisplay .. SV:T("Version") .. ": " ..  infos.versionNumber
		if self.displayAuthor then
			self.infosToDisplay = self.infosToDisplay .. " - " .. SV:T("author") .. ": " .. infos.author
		end
	end
	-- self.infosToDisplay = self.infosToDisplay .. SV:T("minEditorVersion") .. ": " ..  infos.minEditorVersion
	self:addTextPanel(self.infosToDisplay)
	self:addTextPanel(SV:T("Transpose notes") .. "...")
	
	-- Register editor selection callback
	self:registerEditorSelectionCallback()
	self:addNoteInfoPanel(SV:T("Infos on selected notes"))

    return self
end

-- Register arrangement selection callback
function NotesObject:registerEditorSelectionCallback()
	
	-- Register selection callback to load parameters when selection changes
	SV:getMainEditor():getSelection():registerSelectionCallback(function(selectionType, isSelected)
		if selectionType == "note" then
			self:onSelectionChanged()
		end
	end)
	
	-- Register clear selection callback
	SV:getMainEditor():getSelection():registerClearCallback(function(selectionType)
		if selectionType == "note" then
			self:onSelectionChanged()
		end
	end)
end

-- on note selection change
function NotesObject:onSelectionChanged()
	local selection = SV:getMainEditor():getSelection()
	local selectedNotes = selection:getSelectedNotes()
	self:clearNoteInfoPanel()
	
	if #selectedNotes > 0 then
		local currentGroupRef = SV:getMainEditor():getCurrentGroup()
		local timeOffset = currentGroupRef:getTimeOffset()
		if #selectedNotes == 1 then
			local note = selectedNotes[1]
			local key = self.keyNames[note:getPitch() % 12 + 1]
			local keyInfo = key .. (math.floor(note:getPitch()/12) - 1)
			self:addNoteInfoPanel(SV:T("Note: ") .. keyInfo)
			self:addNoteInfoPanel(SV:T("Lyrics: ") .. note:getLyrics())
			self:addNoteInfoPanel(SV:T("Time: ") .. self:secondsToClock(self:getTimeAxis():getSecondsFromBlick(note:getOnset())))
			self:addNoteInfoPanel(SV:T("Track time: ") .. self:secondsToClock(self:getTimeAxis():getSecondsFromBlick(note:getOnset() + timeOffset)))
			if self.displayBlicks then
				self:addNoteInfoPanel(SV:T("Blicks: ") .. note:getOnset())
			end
			if self.isPlayNoteActive then
				local posNoteBeginSecond = self:getTimeAxis():getSecondsFromBlick(note:getOnset() + timeOffset)
				local posNoteEndSecond = self:getTimeAxis():getSecondsFromBlick(note:getEnd() + timeOffset)
				self:startToPlayNotes(posNoteBeginSecond, posNoteEndSecond)
			end
		else
			self:addNoteInfoPanel(SV:T("Selected notes: ") .. #selectedNotes)
			local keys = ""
			for i = 1, #selectedNotes do
				local note = selectedNotes[i]
				local key = self.keyNames[note:getPitch() % 12 + 1]
				keys = keys .. key .. " "
			end
			if #keys > 20 then
				keys = keys:sub(1,20) .. SV:T("...")
			end
			self:addNoteInfoPanel(SV:T("Notes: ") .. keys)
			self:addNoteInfoPanel(SV:T("Time: ") .. self:secondsToClock(self:getTimeAxis():getSecondsFromBlick(selectedNotes[1]:getOnset())))
			self:addNoteInfoPanel(SV:T("Track time: ") .. self:secondsToClock(self:getTimeAxis():getSecondsFromBlick(selectedNotes[1]:getOnset() + timeOffset)))
			if self.isPlayNoteActive then
				local posNoteBeginSecond = self:getTimeAxis():getSecondsFromBlick(selectedNotes[1]:getOnset() + timeOffset)
				local posNoteEndSecond = self:getTimeAxis():getSecondsFromBlick(selectedNotes[#selectedNotes]:getEnd() + timeOffset)
				self:startToPlayNotes(posNoteBeginSecond, posNoteEndSecond)			
			end
		end
	else
		self:clearNoteInfoPanel()
	end
end

-- Start to play note
function NotesObject:startToPlayNotes(posNoteBeginSecond, posNoteEndSecond)
	-- Play note
	self.currentPlayheadPos = SV:getPlayback():getPlayhead()
	SV:getPlayback():seek(posNoteBeginSecond)
	SV:getPlayback():play()
	SV:setTimeout(200, function() self:playNote(posNoteEndSecond) end)
end

-- Play note
function NotesObject:playNote(posNoteEndSecond)
	-- SV:getPlayback():loop(posNoteBeginSecond, posNoteEndSecond)
	if SV:getPlayback():getPlayhead() > posNoteEndSecond then
		SV:getPlayback():stop()
		SV:getPlayback():seek(self.currentPlayheadPos)
	else
		if SV:getPlayback():getStatus() == "looping" or SV:getPlayback():getStatus() == "playing"  then
			SV:setTimeout(200, function() self:playNote(posNoteEndSecond) end)
		end
	end
end

-- Trim string
function NotesObject:trim(s)
  return s:match'^()%s*$' and '' or s:match'^%s*(.*%S)'
end

-- Simple trim string
function NotesObject:simpleTrim(s)
  return string.gsub(s, '[ \t]+%f[\r\n%z]', '')
end


-- Show message dialog
function NotesObject:show(message)
	SV:showMessageBox(SV:T(SCRIPT_TITLE), message)
end

-- Get selected groups
function NotesObject:getSelectedGroups()
	return SV:getArrangement():getSelection():getSelectedGroups()
end

-- Get current track
function NotesObject:getCurrentTrack()
	return SV:getMainEditor():getCurrentTrack()
end

-- Get timeAxis
function NotesObject:getTimeAxis()
	return self:getProject():getTimeAxis()
end

-- Get project
function NotesObject:getProject()
	return SV:getProject()
end

-- Add log into self.logs
function NotesObject:addLogs(message)
	table.insert(self.logs, message)
end

-- Display logs into panel
function NotesObject:addLogsInPanel()
	for i = 1, #self.logs do
		self:addTextPanel(self.logs[i])
	end
end

-- Store error message
function NotesObject:error(message)
	table.insert(self.errorMessages, message)
end

-- Display error messages
function NotesObject:displayErrors()
	local result = ""
	if #self.errorMessages > 0 then
		for _, m in pairs(self.errorMessages) do
			result = result .. m .. "\r"
		end
	end
	return result
end

-- Get host informations
function NotesObject:getHostInformations()
	self.hostinfo = SV:getHostInfo()
	self.osType = self.hostinfo.osType  -- "macOS", "Linux", "Unknown", "Windows"
	self.osName = self.hostinfo.osName
	self.hostName = self.hostinfo.hostName
	self.languageCode = self.hostinfo.languageCode
	self.hostVersion = self.hostinfo.hostVersion
	self.hostVersionNumber = self.hostinfo.hostVersionNumber
end

-- Get controls panel
function NotesObject:getControls()

	local controls = {
		transposeSemitone = {
			value = SV:create("WidgetValue"),	-- Slider
			defaultValue = self.transposeSemitone,
			paramKey = "transposeSemitone"
		},
		isDisplayNoteInfos = {				-- checkbox
			value = SV:create("WidgetValue"),
			defaultValue = self.isDisplayNoteInfos,
			paramKey = "isDisplayNoteInfos"
		},
		isPlayNoteActive = {				-- checkbox
			value = SV:create("WidgetValue"),
			defaultValue = self.isPlayNoteActive,
			paramKey = "isPlayNoteActive"
		},
		isLimitedToSelectedGroups = {			-- checkbox
			value = SV:create("WidgetValue"),
			defaultValue = true,
			paramKey = "isLimitedToSelectedGroups"
		}
		
	}
	return controls
end

-- Initialize widget values
function NotesObject:initializeControlsValues()
	-- Initialize widget values
	for key, control in pairs(self.controls) do
		control.value:setValue(control.defaultValue)
	end
end

-- Set controls callback
function NotesObject:setControlsCallback()
	for key, control in pairs(self.controls) do
		control.value:setValueChangeCallback(function()
			-- self:addLogsInPanel()
			if control.paramKey == "transposeSemitone" then
				self.transposeSemitone = self.controls.transposeSemitone.value:getValue()
				SV:refreshSidePanel()
			end
			if control.paramKey == "isLimitedToSelectedGroups" then
				self.isLimitedToSelectedGroups = self.controls.isLimitedToSelectedGroups.value:getValue()
				SV:refreshSidePanel()
			end
			if control.paramKey == "isDisplayNoteInfos" then
				self.isDisplayNoteInfos = self.controls.isDisplayNoteInfos.value:getValue()
				
				if self.isDisplayNoteInfos then
					self.isPlayNoteActive = false
					self.controls.isPlayNoteActive.value:setValue(self.isPlayNoteActive)
				end
				SV:refreshSidePanel()
			end
			if control.paramKey == "isPlayNoteActive" then
				self.isPlayNoteActive = self.controls.isPlayNoteActive.value:getValue()
				-- SV:refreshSidePanel()
			end
		end
		)
	end
end

-- Display message
function NotesObject:displayMessage(message)
	self:clearTextPanel()
	self:addTextPanel(self.infosToDisplay)
	self:addTextPanel(message)
end

-- Set button transpose notes control callback
function NotesObject:setButtonTransposeNotesControlCallback()

	-- Button transpose notes
	self.transposeNotesValue:setValueChangeCallback(function()
			self:getProject():newUndoRecord()			
			self:transposeNotes()
		end
	)
end

-- Transpose notes
function NotesObject:transposeNotes()
	self.transposeSemitone = self.controls.transposeSemitone.value:getValue()	
	self.isLimitedToSelectedGroups = self.controls.isLimitedToSelectedGroups.value:getValue()
	
	if self.isLimitedToSelectedGroups then
		local groupsSelected = self:getSelectedGroups()
		if #groupsSelected > 0 then
			for _, refGroup in pairs(groupsSelected) do
				local noteGroup = refGroup:getTarget()
				noteGroup:setName(noteGroup:getName() .. self.updatedGroupChar)
				local notesCount = noteGroup:getNumNotes()
				
				if notesCount > 0 then
					-- For each selected notes
					for iNote = 1, notesCount do
						local note = noteGroup:getNote(iNote)
						-- Set new pitch
						note:setPitch(note:getPitch() + self.transposeSemitone)
					end
				end
			end
		else
			-- No group selected
			self:show(SV:T("Select at least one group!"))
		end
	else
		-- All track all groups
		local numTrack = self:getProject():getNumTracks()
		
		for iTrack = 1, numTrack do
			local track = self:getProject():getTrack(iTrack)
			local numGroups = track:getNumGroups()
			
			for iGroup = 1, numGroups do
				local refGroup = track:getGroupReference(iGroup)				
				local noteGroup = refGroup:getTarget()
				noteGroup:setName(noteGroup:getName() .. "*")
				local numNotes = noteGroup:getNumNotes()
				
				for iNote = 1, numNotes do
					local note = noteGroup:getNote(iNote)
					-- Set new pitch
					note:setPitch(note:getPitch() + self.transposeSemitone)
				end
			end
		end
	end
	
end

-- Get object properties
function NotesObject:getObjectProperties(obj, level)
	local result = ""
	local level = level or 0
	local maxLevel = 3
	level = level + 1
	
	for k, v in pairs(obj) do
		if obj[k] ~= nil then
			result = result .. "(level: " .. level .. ") " .. k .. "=" .. tostring(v) .. "\r"
			if type(v) == "table" then
				result = result .. ", size:" .. #v .. ": "
				if level < maxLevel then
					result = result .. getObjectProperties(v, level) .. "\r"
				else
					result = result .. "\r"
				end
			end
		end
	end
	return result
end

-- Get string format from seconds
function NotesObject:secondsToClock(timestamp)
	return string.format("%01dmn %02.1fs",
	  math.floor(timestamp/60)%60, 
	  timestamp%60):gsub("%.",",")
end

-- Split string by sep char
function NotesObject:split(str, sep)
   local result = {}
   local regex = ("([^%s]+)"):format(sep)
   for each in str:gmatch(regex) do
	  table.insert(result, each)
   end
   return result
end

-- Display message box in panel
function NotesObject:addTextPanel(message)
	local old = self.statusTextValue:getValue()
	local sepLine = "\r"
	if #old > 0 then
		message = old .. sepLine .. message
	end
	self.statusTextValue:setValue(message)
end

-- Clear display message in panel
function NotesObject:clearTextPanel()
	self.statusTextValue:setValue("")
end

-- Display note info in panel
function NotesObject:addNoteInfoPanel(message)
	local old = self.statusNoteValue:getValue()
	local sepLine = "\r"
	if #old > 0 then
		message = old .. sepLine .. message
	end
	self.statusNoteValue:setValue(message)
end

-- Clear display note info in panel
function NotesObject:clearNoteInfoPanel()
	self.statusNoteValue:setValue("")
end

-- Get current project tempo
function NotesObject:getProjectTempo(seconds)
	local tempoActive = 120
	local blicks = self:getTimeAxis():getBlickFromSeconds(seconds)
	local tempoMarks = self:getTimeAxis():getAllTempoMarks()
	for iTempo = 1, #tempoMarks do
		local tempoMark = tempoMarks[iTempo]
		if tempoMark ~= nil and blicks >= tempoMark.position then
			tempoActive = tempoMark.bpm
		end
	end
	return math.floor(tempoActive)
end


-- Get section
function NotesObject:getSection()
	local infoNoteDisplay = {}
	local playNoteActive = {}
	local transposeSemitoneDisplay = SV:T("Transpose")
	
	self.transposeNotesValue:setEnabled(self.transposeSemitone ~= 0)
	
	if self.transposeSemitone == 0 then
		transposeSemitoneDisplay = SV:T("Select a value")
	end
	if self.transposeSemitone ~= 0 then
		local sign = ""
		if self.transposeSemitone > 0 then
			sign = SV:T("+")
		end
		transposeSemitoneDisplay = transposeSemitoneDisplay .. " " .. SV:T("to") .. " " .. sign .. string.format("%0d", self.transposeSemitone)
	end
	
	if not self.isLimitedToSelectedGroups then
		transposeSemitoneDisplay = transposeSemitoneDisplay .. " " .. SV:T("in all tracks")
	end
	
	self.controls.isLimitedToSelectedGroups.value:setValue(self.isLimitedToSelectedGroups)
	local limitedToSelectedGroups = 
		{
			type = "Container",
			columns = {
				{
				type = "CheckBox",
				text = SV:T("Limited to selected groups"), -- (else all groups on all tracks)
				value = self.controls.isLimitedToSelectedGroups.value,
				width = 1.0
				}
			}
		}
		
	self.controls.isDisplayNoteInfos.value:setValue(self.isDisplayNoteInfos)
	local displayNoteInfos = 
		{
			type = "Container",
			columns = {
				{
				type = "CheckBox",
				text = SV:T("Display note infos"),
				value = self.controls.isDisplayNoteInfos.value,
				width = 1.0
				}
			}
		}
		
	self.controls.isPlayNoteActive.value:setValue(self.isPlayNoteActive)
	if self.isDisplayNoteInfos then
		playNoteActive = 
			{
				type = "Container",
				columns = {
					{
					type = "CheckBox",
					text = SV:T("Play notes"),
					value = self.controls.isPlayNoteActive.value,
					width = 1.0
					}
				}
			}
			
		infoNoteDisplay = 
			{
				type = "Container",
				columns = {
					{
						type = "TextArea",
						value = self.statusNoteValue,
						height = self.displayBlicksSize,
						width = 1.0,
						readOnly = true
					}
				}
			}
	end

	-- Define CheckBox & button & textarea
	local section = {
		title = SV:T(SCRIPT_TITLE),
		rows = {
			displayNoteInfos,
			infoNoteDisplay,
			playNoteActive,
			{
				type = "Container",
				columns = {
				  {
					type = "Slider",
					text = SV:T("Transpose notes (semitones)"),
					format = "%1.0f",
					minValue = self.transposeMinValue,
					maxValue = self.transposeMaxValue,
					interval = self.transposeInterval,
					value = self.controls.transposeSemitone.value,
					width = 1
				  }
				}
			},
			limitedToSelectedGroups,
			{
				type = "Container",
				columns = {
					{
						type = "Button",
						text = transposeSemitoneDisplay,
						width = 1.0,
						value = self.transposeNotesValue
					}
				}
			},
			{
				type = "Container",
				columns = {
					{
						type = "TextArea",
						value = self.statusTextValue,
						height = 40,
						width = 1.0,
						readOnly = true
					}
				}
			}
		}
	}
	return section
end

-- Get panel section state
function NotesObject:getPanelSectionState()
	
	local errors = self:displayErrors()
	if #errors > 0 then
		self:addTextPanel(errors)
	end
	
	-- Get section data
	local section = self:getSection()

	return section
end

-- Initialize main internal object	
local notesObject = NotesObject:new()

-- Get panel section state called by Synthesizer V internal system
function getSidePanelSectionState()

	local section = notesObject:getPanelSectionState()

	return section
end
