local SCRIPT_TITLE = 'Shift notes left V1.0'

--[[

Synthesizer V Studio Pro Script
 
lua file name: ShiftNotesLeft.lua

This script will move notes left
on selected notes.
If no notes selected piano-roll scroll left

Set shortcut to Cursor left

2025 - JF AVILES
--]]

-- Generated by JFA TranslateScripts.lua
function getTranslations(langCode)
	return getArrayLanguageStrings()[langCode]
end

-- Generated by JFA TranslateScripts.lua
function getArrayLanguageStrings()
	return {
		["en-us"] = {
			-- {"Comment!", "Comment!"},
		},
	}
end

function getClientInfo()
	return {
		name = SV:T(SCRIPT_TITLE),
		category = "_JFA_Tools",
		author = "JFAVILES",
		versionNumber = 1,
		minEditorVersion = 65540
	}
end

-- Define a class  "NotesObject"
NotesObject = {
	project = nil,
	timeAxis = nil,
	arrangement = nil,
	editor = nil,
	direction = -1, -- direction (left = -1 & right = +1)
	noteTimeGap = SV.QUARTER / 4, -- moving left/right QUARTER/4
	navigation = nil,
	selectedNotes = nil
}

-- Constructor method for the NotesObject class
function NotesObject:new()
    local notesObject = {}
    setmetatable(notesObject, self)
    self.__index = self
	
    self.project = SV:getProject()
    self.timeAxis = self.project:getTimeAxis()
    self.editor =  SV:getMainEditor()
	self.selectedNotes = self.editor:getSelection():getSelectedNotes()
	self.navigation = self.editor:getNavigation()
	
    return self
end

-- Display message box
function NotesObject:show(message)
	SV:showMessageBox(SV:T(SCRIPT_TITLE), message)
end

-- Start processing
function NotesObject:start()	
	
	-- Notes selected
	if #self.selectedNotes > 0 then
		-- For each selected notes
		for _, note in pairs(self.selectedNotes) do			
			-- Set new position			
			note:setOnset(note:getOnset() + (self.noteTimeGap * self.direction))
		end
	else
		-- No notes selected
		local timeViewRange = self.navigation:getTimeViewRange()
		local newPos = timeViewRange[1] + (self.noteTimeGap * self.direction)
		-- Scroll left/right
		self.navigation:setTimeLeft(newPos)
	end
end

-- Main process
function main()
	local notesObject = NotesObject:new()

	-- Start process
	notesObject:start()
	
	SV:finish()
end